config/routes.rb
Rails.application.routes.draw do


  resources :caseworklinethings
  resources :caseworklinekinds
  resources :things
  resources :kinds

  resources :caseworkesselines
  resources :dutyworks
  resources :dutydeals
  resources :dutyitems
  # resources :caseworks

  resources :esses, :esselines

  resources :caseitems, :casedeals, :caseflowworks, :caseworks, :caseworklines

  resources :flowdeals, :flowworks

  resources :flowitems do
    resources :flowdeals do
      resources :flowworks
    end
    get 'search', on: :collection
  end

  resources :unititems, :unitdeals, :unitworks
  resources :roleconfigs
  resources :roles
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :kinds do
    get  'addthing' => :addthing

  end



  resources :caseworks do
    resources :caseworklines
    resources :caseworkesselines
  end

  resources :caseworks do
    resources :caseworklinekinds
    resources :caseworklinethings
        # get 'clone', on: :member
    # get 'copyform', on: :member
  end


  resources :caseworks do
    resources :kinds
    resources :things
  end
  # get 'admin/index'
  #
  # get 'sessions/new'
  #
  # get 'sessions/create'
  #
  # get 'sessions/destroy'

  resources :users
  root 'unititems#index', as: 'unititems_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dutydeal.rb
class Dutydeal < ApplicationRecord
  belongs_to :dutyitem
  belongs_to :flowdeal
  has_many :dutyworks

  enum seltype: {"s_yes" => 1,"s_no" => 2}
  validates :seltype, inclusion: seltypes.keys

  enum addtype: {"a_yes" => 1,"a_no" => 2}
  validates :addtype, inclusion: addtypes.keys

  enum updtype: {"u_yes" => 1, "u_no" => 2}
  validates :updtype, inclusion: updtypes.keys

  enum deltype: {"d_yes" => 1,"d_no" => 2}
  validates :deltype, inclusion: deltypes.keys



end

app/controllers/dutydeals_controller.rb
class DutydealsController < ApplicationController
  before_action :set_dutydeal, only: [:show, :edit, :update, :destroy]

  # GET /dutydeals
  # GET /dutydeals.json
  def index
    @dutydeals = Dutydeal.all
  end

  # GET /dutydeals/1
  # GET /dutydeals/1.json
  def show
  end

  # GET /dutydeals/new
  def new
    @dutydeal = Dutydeal.new
  end

  # GET /dutydeals/1/edit
  def edit
  end

  # POST /dutydeals
  # POST /dutydeals.json
  def create
    @dutydeal = Dutydeal.new(dutydeal_params)

    respond_to do |format|
      if @dutydeal.save
        format.html { redirect_to @dutydeal, notice: 'Dutydeal was successfully created.' }
        format.json { render :show, status: :created, location: @dutydeal }
      else
        format.html { render :new }
        format.json { render json: @dutydeal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dutydeals/1
  # PATCH/PUT /dutydeals/1.json
  def update
    respond_to do |format|
      if @dutydeal.update(dutydeal_params)
        format.html { redirect_to @dutydeal, notice: 'Dutydeal was successfully updated.' }
        format.json { render :show, status: :ok, location: @dutydeal }
      else
        format.html { render :edit }
        format.json { render json: @dutydeal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dutydeals/1
  # DELETE /dutydeals/1.json
  def destroy
    @dutydeal.destroy
    respond_to do |format|
      format.html { redirect_to dutydeals_url, notice: 'Dutydeal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dutydeal
      @dutydeal = Dutydeal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dutydeal_params
      params.require(:dutydeal).permit(:dutyitem_id, :flowdeal_id, :seltype, :addtype, :updtype, :deltype)
    end
end

app/helpers/dutydeals_helper.rb
module DutydealsHelper
end

app/views/dutydeals/_form.html.erb
<%= form_with(model: dutydeal, local: true) do |form| %>
  <% if dutydeal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dutydeal.errors.count, "error") %> prohibited this dutydeal from being saved:</h2>

      <ul>
      <% dutydeal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dutyitem_id %>
    <%= form.select :dutyitem_id, Dutyitem.all.collect {|p| [ p.role.name + p.flowitem.name, p.id ] } %>
  </div>

  <div class="field">
    <%= form.label :flowdeal_id %>
    <%= form.select :flowdeal_id,
    Flowdeal.all.collect {|p| [ p.unitdeal.name, p.id ] } %>
    <!-- dutydeal.dutyitem.flowitem_id -->
  </div>

  <div class="field">
    <%= form.label :seltype %>
    <%= form.select :seltype, Dutyitem.seltypes.keys %>
  </div>

  <div class="field">
    <%= form.label :addtype %>
    <%= form.select :addtype, Dutyitem.addtypes.keys %>
  </div>

  <div class="field">
    <%= form.label :updtype %>
    <%= form.select :updtype, Dutyitem.updtypes.keys %>
  </div>

  <div class="field">
    <%= form.label :deltype %>
    <%= form.select :deltype, Dutyitem.deltypes.keys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dutydeals/edit.html.erb
<h1>Editing Dutydeal</h1>

<%= render 'form', dutydeal: @dutydeal %>

<%= link_to 'Show', @dutydeal %> |
<%= link_to 'Back', dutydeals_path %>

app/views/dutydeals/index.html.erb
<p id="notice"><%= notice %></p>

<!-- header -->
<div class="card-header bg-transparent border-first">
  <div class="card-block border-0">
    <h1>Dutydeals</h1>
  </div>
</div>
<!-- body -->
<div class="card-body text-first border-first">
  <table class="table table-sm table-striped">
   <thead class="thead-dark">
    <tr>
      <th>Role1</th>
      <th>Id</th>
      <th>Flowitem</th>
      <th>Flowdeal</th>
      <th>Seltype</th>
      <th>Addtype</th>
      <th>Updtype</th>
      <th>Deltype</th>
      <th colspan="3"></th>
    </tr>
   </thead>


   <tbody>
     <% @dutydeals.each do |dutydeal| %>
       <tr>
         <td><%= dutydeal.dutyitem.role.name %></td>
         <td><%= link_to dutydeal.id, edit_dutydeal_path(dutydeal) %></td>
         <td><%=  dutydeal.flowdeal.flowitem.name %></td>
         <td><%= link_to dutydeal.flowdeal.unitdeal.name, dutydeal %></td>
         <td><%= dutydeal.seltype %></td>
         <td><%= dutydeal.addtype %></td>
         <td><%= dutydeal.updtype %></td>
         <td><%= dutydeal.deltype %></td>

         <td><%= link_to 'Destroy', dutydeal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
     <% end %>
   </tbody>

   <tfoot>
    <tr >

    </tr>
   </tfoot>
  </table>
</div>
<!-- footer -->
<div class="card-footer bg-transparent border-first">


  <%= link_to 'New Dutydeal', new_dutydeal_path %>
</div>

app/views/dutydeals/new.html.erb
<h1>New Dutydeal</h1>

<%= render 'form', dutydeal: @dutydeal %>

<%= link_to 'Back', dutydeals_path %>

app/views/dutydeals/show.html.erb
<p id="notice"><%= notice %></p>
<!-- header -->
<div class="card-header bg-transparent border-first">
  <div class="card-block border-0">
    <h1>dutydeal</h1>
  </div>
</div>
<div class="card-header bg-transparent border-first">
  <div class="card-block border-0">
    <p>
      <strong>Dutyitem:</strong>
      <%= link_to @dutydeal.dutyitem.flowitem.name, dutyitem_path(@dutydeal.dutyitem) %>
    </p>

    <p>
      <strong>Flowdeal:</strong>
      <%= @dutydeal.flowdeal.unitdeal.name %>
    </p>

    <p>
      <strong>Seltype:</strong>
      <%= @dutydeal.seltype %>
    </p>

    <p>
      <strong>Addtype:</strong>
      <%= @dutydeal.addtype %>
    </p>

    <p>
      <strong>Updtype:</strong>
      <%= @dutydeal.updtype %>
    </p>

    <p>
      <strong>Deltype:</strong>
      <%= @dutydeal.deltype %>
    </p>
  </div>
</div>
<!-- body -->
<div class="card-body text-first border-first">
  <table class="table table-sm table-striped">
   <thead class="thead-dark">
    <tr>

      <th>Dutywork Id</th>

      <th>Dutywork</th>
      <th>Seltype</th>
      <th>Addtype</th>
      <th>Updtype</th>
      <th>Deltype</th>
      <th colspan="3"></th>
    </tr>
   </thead>

   <tbody>
     <% @dutydeal.dutyworks.each do |dutywork| %>
       <tr>

         <td><%= link_to dutywork.id, edit_dutywork_path(dutywork) %></td>

         <td><%= link_to dutywork.flowwork.unitwork.name, dutywork %></td>
         <td><%= dutywork.seltype %></td>
         <td><%= dutywork.addtype %></td>
         <td><%= dutywork.updtype %></td>
         <td><%= dutywork.deltype %></td>

         <td><%= link_to 'Destroy', dutywork, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
     <% end %>
   </tbody>

   <tfoot>
    <tr >

    </tr>
   </tfoot>
  </table>
</div>
<!-- footer -->
<div class="card-footer bg-transparent border-first">
  <%= link_to 'Edit', edit_dutydeal_path(@dutydeal) %> |
  <%= link_to 'Back', dutydeals_path %>
  <%= link_to 'New Dutydeal', new_dutywork_path %>
</div>