config/routes.rb
Rails.application.routes.draw do


  resources :caseworklinethings
  resources :caseworklinekinds
  resources :things
  resources :kinds

  resources :caseworkesselines
  resources :dutyworks
  resources :dutydeals
  resources :dutyitems
  # resources :caseworks

  resources :esses, :esselines

  resources :caseitems, :casedeals, :caseflowworks, :caseworks, :caseworklines

  resources :flowdeals, :flowworks

  resources :flowitems do
    resources :flowdeals do
      resources :flowworks
    end
    get 'search', on: :collection
  end

  resources :unititems, :unitdeals, :unitworks
  resources :roleconfigs
  resources :roles
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :kinds do
    get  'addthing' => :addthing

  end



  resources :caseworks do
    resources :caseworklines
    resources :caseworkesselines
  end

  resources :caseworks do
    resources :caseworklinekinds
    resources :caseworklinethings
        # get 'clone', on: :member
    # get 'copyform', on: :member
  end


  resources :caseworks do
    resources :kinds
    resources :things
  end
  # get 'admin/index'
  #
  # get 'sessions/new'
  #
  # get 'sessions/create'
  #
  # get 'sessions/destroy'

  resources :users
  root 'unititems#index', as: 'unititems_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/caseitem.rb
class Caseitem < ApplicationRecord
  belongs_to :flowitem
  has_many :casedeals
  has_many :caseworklines

  def seltype_caseitems(user_id)
    @caseitem=Caseitem.where(flowitem_id: 4)
    # return
  end

  def copy_flowdeals_to_casedeals(caseitem)
    caseitem.flowitem.flowdeals.each do |flowdeal|
      @casedeal = Casedeal.new
      @casedeal.name = flowdeal.unitdeal.name
      @casedeal.caseitem_id = caseitem.id
      @casedeal.dealtype = flowdeal.dealtype
      @casedeal.floworderid = flowdeal.floworderid
      @casedeal.flowtype = flowdeal.flowtype

      @casedeal.save

      flowdeal.flowworks.each do |flowwork|
        @caseflowwork = Caseflowwork.new
        @caseflowwork.code = flowwork.unitwork.code
        @caseflowwork.name = flowwork.unitwork.name
        @caseflowwork.casedeal_id = @casedeal.id
        puts @caseflowwork.name
        @caseflowwork.accouttype = flowwork.accouttype
        @caseflowwork.floworderid = flowwork.floworderid
        @caseflowwork.flowtype = flowwork.flowtype

        @caseflowwork.vouchertemplatetype = flowwork.vouchertemplatetype
        @caseflowwork.contenttype = flowwork.contenttype
        @caseflowwork.resourcestype = flowwork.resourcestype

        @caseflowwork.subdealtype = flowwork.subdealtype
        @caseflowwork.stockaccounttype = flowwork.stockaccounttype
        @caseflowwork.copyresourcestype = flowwork.copyresourcestype

        @caseflowwork.beforeunitwork_id = flowwork.beforeunitwork_id
        @caseflowwork.afterunitwork_id = flowwork.afterunitwork_id

        @caseflowwork.save

      end
      # puts @casedeal.id
      # puts @casedeal.name
      # puts @casedeal.caseitem_id
      # puts @casedeal.dealtype
      # puts @casedeal.floworderid
      # puts @casedeal.flowtype



    end
  end

end

app/controllers/caseitems_controller.rb
class CaseitemsController < ApplicationController
  before_action :set_caseitem, only: [:show, :edit, :update, :destroy]

  # GET /caseitems
  # GET /caseitems.json
  def index
    @caseitems = Caseitem.all
    # @caseitems = Caseitem.where(flowitem_id: 4)
    # get list for caseitems by flowitem_id by role_id by user_id
    # @caseitem.seltype_caseitems(@caseitem)
  end

  # GET /caseitems/1
  # GET /caseitems/1.json
  def show
  end

  # GET /caseitems/new
  def new
    @caseitem = Caseitem.new
  end

  # GET /caseitems/1/edit
  def edit
  end

  # POST /caseitems
  # POST /caseitems.json
  def create
    @caseitem = Caseitem.new(caseitem_params)

    respond_to do |format|
      if @caseitem.save
        # copy flowdeals to casedeals
        @caseitem.copy_flowdeals_to_casedeals(@caseitem)

        format.html { redirect_to caseitems_url, notice: 'Caseitem was successfully created.' }
        format.json { render :show, status: :created, location: @caseitem }
      else
        format.html { render :new }
        format.json { render json: @caseitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caseitems/1
  # PATCH/PUT /caseitems/1.json
  def update
    respond_to do |format|
      if @caseitem.update(caseitem_params)
        format.html { redirect_to caseitems_url, notice: 'Caseitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @caseitem }
      else
        format.html { render :edit }
        format.json { render json: @caseitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caseitems/1
  # DELETE /caseitems/1.json
  def destroy
    @caseitem.destroy
    respond_to do |format|
      format.html { redirect_to caseitems_url, notice: 'Caseitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caseitem
      @caseitem = Caseitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caseitem_params
      params.require(:caseitem).permit(:code, :name, :flowitem_id, :status, :remarks)
    end
end

app/helpers/caseitems_helper.rb
module CaseitemsHelper
end

app/views/caseitems/_form.html.erb
<%= form_with(model: caseitem, local: true) do |form| %>
  <% if caseitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caseitem.errors.count, "error") %> prohibited this caseitem from being saved:</h2>

      <ul>
      <% caseitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :caseitem_code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :caseitem_name %>
  </div>


  <div class="field">
    <%= form.label :flowitem_id,"Flowitem" %>
    <%= form.select :flowitem_id, Flowitem.all.collect {|p| [ p.name, p.id ] } %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :caseitem_status %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks, id: :caseitem_remarks %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/caseitems/edit.html.erb
<h1>Editing Caseitem</h1>

<%= render 'form', caseitem: @caseitem %>

<%= link_to 'Show', @caseitem %> |
<%= link_to 'Back', caseitems_path %>

app/views/caseitems/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Caseitems</h3>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Flowitem</th>
      <th>Status</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caseitems.each do |caseitem| %>
      <tr>
        <td><%= caseitem.code %></td>
        <td><%= caseitem.name %></td>
        <td><%= caseitem.flowitem.name %></td>

        <td><%= caseitem.status %></td>
        <td><%= caseitem.remarks %></td>

        <td><%=
          if (Dutyitem.where(role_id: Roleconfig.where(user_id:session[:user_id]).pluck(:role_id),
            flowitem_id: caseitem.flowitem_id).limit(1).pluck(:seltype) == ["s_yes"])
          then link_to 'Show', caseitem
          else '----'
          end
          %>
        </td>
        <td><%=
          if (Dutyitem.where(role_id: Roleconfig.where(user_id:session[:user_id]).pluck(:role_id),
            flowitem_id: caseitem.flowitem_id).limit(1).pluck(:updtype) == ["u_yes"])
          then link_to 'Edit', edit_caseitem_path(caseitem)
          else '----'
          end
          %>
        </td>
        <td><%=
          if (Dutyitem.where(role_id: Roleconfig.where(user_id:session[:user_id]).pluck(:role_id),
            flowitem_id: caseitem.flowitem_id).limit(1).pluck(:deltype) == ["d_yes"])
          then link_to 'Des', caseitem, method: :delete, data: { confirm: 'Are you sure?' }
          else '----'
          end
          %>
        </td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caseitem', new_caseitem_path %>

app/views/caseitems/new.html.erb
<h1>New Caseitem</h1>

<%= render 'form', caseitem: @caseitem %>

<%= link_to 'Back', caseitems_path %>

app/views/caseitems/show.html.erb
<p id="notice"><%= notice %></p>
<div  class="card  mb-3">
  <!-- caseitem_title -->
  <div class="card-header  border-first">
      <div class="card-block">
        <h6 class="card-title">
          <%= @caseitem.name %>: <%= @caseitem.id %>
        </h6>
      </div>
  </div>
  <!-- caseitem -->
  <div class="card-body">
      <div class="p-1 form-group row">
        <div class="col-sm-4"><p>代码：<%= @caseitem.code %></p></div>
        <div class="col-sm-4"><p>名称：<%= @caseitem.name %></p></div>
        <div class="col-sm-4"><p>状态：<%= @caseitem.status %></p></div>
        <div class="col-sm-4"><p>日期：<%= @caseitem.created_at.strftime('%Y-%m-%d') %></p></div>
        <div class="col-sm-4"><p>备注：<%= @caseitem.remarks %></p></div>
        <div class="col-sm-4 d-none d-sm-block"><p>桌面显示</p></div>
      </div>
      </div>

<div class="card-body ">
<!-- casedeal -->
  <ul id="mytab" class="nav nav-tabs flex-sm-row">
    <% @caseitem.casedeals.each do |casedeal| %>
      <% if casedeal.floworderid == 1 %>
          <li  class="nav-item">
            <a class="nav-link active show" href="#<%= casedeal.name %>" data-toggle="tab"><%= casedeal.name %></a>
          </li>
       <% else %>
         <li  class="nav-item">
           <a class="nav-link" href="#<%= casedeal.name %>" data-toggle="tab"><%= casedeal.name %></a>
         </li>
      <% end %>
    <% end %>
  </ul><p></p>

<!-- casedeal pane -->
  <div class="tab-content">
      <% @caseitem.casedeals.each do |casedeal| %>
        <% if casedeal.floworderid == 1 %>
          <div class="tab-pane active" id="<%= casedeal.name %>"><!--2 每个交易下的活动集 -->   <!--3 每个活动标题下的实例活动 -->
         <% else %>
          <div class="tab-pane" id="<%= casedeal.name %>">
        <% end %>
        <table>
          <tbody>
            <!-- caseflowwork -->
            <tr>
              <% casedeal.caseflowworks.each do |caseflowwork| %>
                <td>
                  <div class="d-flex align-items-start flex-column" style="height: 200px;">
                      <div class="btn-info btn-sm" >
                        <h7>
                          <%= caseflowwork.name %>
                        </h7>
                      </div>
                      <p></p>
                      <div >
                        <!-- casework -->
                        <% caseflowwork.caseworks.each do |casework| %>
                          <div class="btn btn-danger btn-sm">
                            <% casework.name %>
                            <span class="badge badge-light"><%= link_to casework.id, casework %></span>

                          </div><p></p>
                        <% end %>
                      </div>
                  </div>
                </td>
              <% end %>
            </tr>

          </tbody>
        </table>
          </div>
      <% end %>
    </div>
  </div>

  <div class="card-footer bg-transparent border-first">
    <%= link_to 'Edit', edit_caseitem_path(@caseitem) %> |
    <%= link_to 'Back', caseitems_path %>
  </div>
</div>