config/routes.rb
Rails.application.routes.draw do


  resources :caseworklinethings
  resources :caseworklinekinds
  resources :things
  resources :kinds

  resources :caseworkesselines
  resources :dutyworks
  resources :dutydeals
  resources :dutyitems
  # resources :caseworks

  resources :esses, :esselines

  resources :caseitems, :casedeals, :caseflowworks, :caseworks, :caseworklines

  resources :flowdeals, :flowworks

  resources :flowitems do
    resources :flowdeals do
      resources :flowworks
    end
    get 'search', on: :collection
  end

  resources :unititems, :unitdeals, :unitworks
  resources :roleconfigs
  resources :roles
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :kinds do
    get  'addthing' => :addthing

  end



  resources :caseworks do
    resources :caseworklines
    resources :caseworkesselines
  end

  resources :caseworks do
    resources :caseworklinekinds
    resources :caseworklinethings
        # get 'clone', on: :member
    # get 'copyform', on: :member
  end


  resources :caseworks do
    resources :kinds
    resources :things
  end
  # get 'admin/index'
  #
  # get 'sessions/new'
  #
  # get 'sessions/create'
  #
  # get 'sessions/destroy'

  resources :users
  root 'unititems#index', as: 'unititems_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/casedeal.rb
class Casedeal < ApplicationRecord

  belongs_to :caseitem
  has_many :caseflowworks

  enum dealtype: {
      "Sale"        => 1,
      "Purchase"    => 2,
      "manager"     => 3
    }
    validates :dealtype, inclusion: dealtypes.keys

    enum flowtype: {
    "Test"        => 1,
    "Release"     => 2
    }
    validates :flowtype, inclusion: flowtypes.keys
end

app/controllers/casedeals_controller.rb
class CasedealsController < ApplicationController
  before_action :set_casedeal, only: [:show, :edit, :update, :destroy]

  # GET /casedeals
  # GET /casedeals.json
  def index
    @casedeals = Casedeal.all
  end

  # GET /casedeals/1
  # GET /casedeals/1.json
  def show
  end

  # GET /casedeals/new
  def new
    @casedeal = Casedeal.new
  end

  # GET /casedeals/1/edit
  def edit
  end

  # POST /casedeals
  # POST /casedeals.json
  def create
    @casedeal = Casedeal.new(casedeal_params)

    respond_to do |format|
      if @casedeal.save
        format.html { redirect_to casedeals_url, notice: 'Casedeal was successfully created.' }
        format.json { render :show, status: :created, location: @casedeal }
      else
        format.html { render :new }
        format.json { render json: @casedeal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casedeals/1
  # PATCH/PUT /casedeals/1.json
  def update
    respond_to do |format|
      if @casedeal.update(casedeal_params)
        format.html { redirect_to casedeals_url, notice: 'Casedeal was successfully updated.' }
        format.json { render :show, status: :ok, location: @casedeal }
      else
        format.html { render :edit }
        format.json { render json: @casedeal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casedeals/1
  # DELETE /casedeals/1.json
  def destroy
    @casedeal.destroy
    respond_to do |format|
      format.html { redirect_to casedeals_url, notice: 'Casedeal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casedeal
      @casedeal = Casedeal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casedeal_params
      params.require(:casedeal).permit(:name, :caseitem_id, :dealtype, :floworderid, :flowtype)
    end
end

app/helpers/casedeals_helper.rb
module CasedealsHelper
end

app/views/casedeals/_form.html.erb
<%= form_with(model: casedeal, local: true) do |form| %>
  <% if casedeal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(casedeal.errors.count, "error") %> prohibited this casedeal from being saved:</h2>

      <ul>
      <% casedeal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :casedeal_name %>
  </div>

  <div class="field">
    <%= form.label :caseitem_id %>
    <%= form.text_field :caseitem_id, id: :casedeal_caseitem_id %>
  </div>

  <div class="field">
    <%= form.label :dealtype %>
    <%= form.number_field :dealtype, id: :casedeal_dealtype %>
  </div>

  <div class="field">
    <%= form.label :floworderid %>
    <%= form.number_field :floworderid, id: :casedeal_floworderid %>
  </div>

  <div class="field">
    <%= form.label :flowtype %>
    <%= form.number_field :flowtype, id: :casedeal_flowtype %>
  </div>

  <div class="field">
    <%= form.label :dealtype %>
    <%= form.select :dealtype, Flowdeal.dealtypes.keys,
              prompt: "select a dealtype" %>
  </div>

  <div class="field">
    <%= form.label :floworderid %>
    <%= form.number_field :floworderid, id: :flowdeal_floworderid %>
  </div>

  <div class="field">
  <%= form.label :flowtype %>
  <%= form.select :flowtype, Flowdeal.flowtypes.keys,
                prompt: "select a type" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/casedeals/edit.html.erb
<h1>Editing Casedeal</h1>

<%= render 'form', casedeal: @casedeal %>

<%= link_to 'Show', @casedeal %> |
<%= link_to 'Back', casedeals_path %>

app/views/casedeals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Casedeals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Caseitem</th>
      <th>Dealtype</th>
      <th>Floworderid</th>
      <th>Flowtype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casedeals.each do |casedeal| %>
      <tr>
        <td><%= casedeal.name %></td>
        <td><%= casedeal.caseitem.name %></td>
        <td><%= casedeal.dealtype %></td>
        <td><%= casedeal.floworderid %></td>
        <td><%= casedeal.flowtype %></td>
        <td><%= link_to 'Show', casedeal %></td>
        <td><%= link_to 'Edit', edit_casedeal_path(casedeal) %></td>
        <td><%= link_to 'Destroy', casedeal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Casedeal', new_casedeal_path %>

app/views/casedeals/new.html.erb
<h1>New Casedeal</h1>

<%= render 'form', casedeal: @casedeal %>

<%= link_to 'Back', casedeals_path %>

app/views/casedeals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @casedeal.name %>
</p>

<p>
  <strong>Caseitem:</strong>
  <%= @casedeal.caseitem.name %>
</p>

<p>
  <strong>Dealtype:</strong>
  <%= @casedeal.dealtype %>
</p>

<p>
  <strong>Floworderid:</strong>
  <%= @casedeal.floworderid %>
</p>

<p>
  <strong>Flowtype:</strong>
  <%= @casedeal.flowtype %>
</p>

<%= link_to 'Edit', edit_casedeal_path(@casedeal) %> |
<%= link_to 'Back', casedeals_path %>