config/routes.rb
Rails.application.routes.draw do


  resources :caseworklinethings
  resources :caseworklinekinds
  resources :things
  resources :kinds

  resources :caseworkesselines
  resources :dutyworks
  resources :dutydeals
  resources :dutyitems
  # resources :caseworks

  resources :esses, :esselines

  resources :caseitems, :casedeals, :caseflowworks, :caseworks, :caseworklines

  resources :flowdeals, :flowworks

  resources :flowitems do
    resources :flowdeals do
      resources :flowworks
    end
    get 'search', on: :collection
  end

  resources :unititems, :unitdeals, :unitworks
  resources :roleconfigs
  resources :roles
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :kinds do
    get  'addthing' => :addthing

  end



  resources :caseworks do
    resources :caseworklines
    resources :caseworkesselines
  end

  resources :caseworks do
    resources :caseworklinekinds
    resources :caseworklinethings
        # get 'clone', on: :member
    # get 'copyform', on: :member
  end


  resources :caseworks do
    resources :kinds
    resources :things
  end
  # get 'admin/index'
  #
  # get 'sessions/new'
  #
  # get 'sessions/create'
  #
  # get 'sessions/destroy'

  resources :users
  root 'unititems#index', as: 'unititems_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/roleconfig.rb
class Roleconfig < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/roleconfigs_controller.rb
class RoleconfigsController < ApplicationController
  before_action :set_roleconfig, only: [:show, :edit, :update, :destroy]

  # GET /roleconfigs
  # GET /roleconfigs.json
  def index
    @roleconfigs = Roleconfig.all
  end

  # GET /roleconfigs/1
  # GET /roleconfigs/1.json
  def show
  end

  # GET /roleconfigs/new
  def new
    @roleconfig = Roleconfig.new
  end

  # GET /roleconfigs/1/edit
  def edit
  end

  # POST /roleconfigs
  # POST /roleconfigs.json
  def create
    @roleconfig = Roleconfig.new(roleconfig_params)

    respond_to do |format|
      if @roleconfig.save
        format.html { redirect_to @roleconfig, notice: 'Roleconfig was successfully created.' }
        format.json { render :show, status: :created, location: @roleconfig }
      else
        format.html { render :new }
        format.json { render json: @roleconfig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roleconfigs/1
  # PATCH/PUT /roleconfigs/1.json
  def update
    respond_to do |format|
      if @roleconfig.update(roleconfig_params)
        format.html { redirect_to @roleconfig, notice: 'Roleconfig was successfully updated.' }
        format.json { render :show, status: :ok, location: @roleconfig }
      else
        format.html { render :edit }
        format.json { render json: @roleconfig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roleconfigs/1
  # DELETE /roleconfigs/1.json
  def destroy
    @roleconfig.destroy
    respond_to do |format|
      format.html { redirect_to roleconfigs_url, notice: 'Roleconfig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roleconfig
      @roleconfig = Roleconfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roleconfig_params
      params.require(:roleconfig).permit(:user_id, :role_id)
    end
end

app/helpers/roleconfigs_helper.rb
module RoleconfigsHelper
end

app/views/roleconfigs/_form.html.erb
<%= form_with(model: roleconfig, local: true) do |form| %>
  <% if roleconfig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roleconfig.errors.count, "error") %> prohibited this roleconfig from being saved:</h2>

      <ul>
      <% roleconfig.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- header -->
  <div class="card-header bg-transparent border-first">
    <div class="card-block border-0">
      <!-- <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :user_name %>
      </div> -->

      <div class="field">
        <%= form.label :user_id %>
        <%= form.select :user_id, User.all.collect {|p| [ p.name, p.id ] } %>
      </div>

      <!-- <div class="field">
        <%= form.label :user_id %>
        <%= form.text_field :user_id, id: :roleconfig_user_id %>
      </div> -->

      <div class="field">
        <%= form.label :role_id %>
        <%= form.select :role_id, Role.all.collect {|p| [ p.name, p.id ] } %>
      </div>

      <!-- <div class="field">
        <%= form.label :role_id %>
        <%= form.text_field :role_id, id: :roleconfig_role_id %>
      </div> -->

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>

<% end %>

app/views/roleconfigs/edit.html.erb
<h1>Editing Roleconfig</h1>

<%= render 'form', roleconfig: @roleconfig %>

<%= link_to 'Show', @roleconfig %> |
<%= link_to 'Back', roleconfigs_path %>

app/views/roleconfigs/index.html.erb
<p id="notice"><%= notice %></p>

<!-- header -->
<div class="card-header bg-transparent border-first">
  <div class="card-block border-0">
    <h1>Roleconfigs</h1>
  </div>
</div>
<!-- body -->
<div class="card-body text-first border-first">
  <table class="table table-sm table-striped">
   <thead class="thead-dark">
    <tr>
      <th>Id</th>
      <th>User</th>
      <th>Role</th>
      <th>created_at</th>
      <th>updated_at</th>
      <th colspan="3"></th>
    </tr>
   </thead>

   <tbody>
     <% @roleconfigs.each do |roleconfig| %>
       <tr>
         <td><%= link_to roleconfig.id, roleconfig %></td>
         <td><%= link_to roleconfig.user.name, edit_roleconfig_path(roleconfig) %></td>
         <td><%= roleconfig.role.name %></td>
         <td><%= roleconfig.created_at.strftime('%Y-%m-%d') %></td>
         <td><%= roleconfig.updated_at.strftime('%Y-%m-%d') %></td>

         <td><%= link_to 'Destroy', roleconfig, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
     <% end %>
   </tbody>

   <tfoot>
    <tr >

    </tr>
   </tfoot>
  </table>
</div>
<!-- footer -->
<div class="card-footer bg-transparent border-first">
<%= link_to 'New Roleconfig', new_roleconfig_path %>

</div>

app/views/roleconfigs/new.html.erb
<!-- header -->
<div class="card-header bg-transparent border-first">
  <div class="card-block border-0">
    <h1>New Roleconfig</h1>
  </div>
</div>


<%= render 'form', roleconfig: @roleconfig %>
<div class="card-footer bg-transparent border-first">
<%= link_to 'Back', roleconfigs_path %>
</div>

app/views/roleconfigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @roleconfig.user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @roleconfig.role.name %>
</p>

<%= link_to 'Edit', edit_roleconfig_path(@roleconfig) %> |
<%= link_to 'Back', roleconfigs_path %>